# Generated by Django 2.2.7 on 2019-12-27 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_and_me_app', '0002_genre_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='File',
        ),
    ]
